import ToasterContext from '../context/ToasterContext';
import '../globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen relative">
        <div className="dark w-full h-full bg-brand-black  flex justify-center items-center">
          <ToasterContext />
          {children}
        </div>
      </body>
    </html>
  );
}
